modLoader = "javafml"
loaderVersion = "[46,)"
license = "All Rights Reserved"
[[mods]]
modId = "sactweaker"
version = "${file.jarVersion}"
displayName = "SacTweaker"
authors = "JianBi233"
description = ""
